"""user tables created

Revision ID: 83c3aa7fda7b
Revises: 
Create Date: 2025-09-15 16:30:38.641814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c3aa7fda7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    '''with op.batch_alter_table('translations', schema=None) as batch_op:
        #batch_op.create_unique_constraint('unique_word_meaning', ['language', 'text'])'''


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_object_prepositions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_word_preposition_object', type_='unique')
        batch_op.create_index(batch_op.f('_word_preposition_uc'), ['word_id', 'preposition_object_id'], unique=True)

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_constraint('unique_word_meaning', type_='unique')

    op.drop_table('users')
    # ### end Alembic commands ###
