"""roles table added

Revision ID: b7772d767eef
Revises: 83c3aa7fda7b
Create Date: 2025-09-15 18:31:57.438870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7772d767eef'
down_revision = '83c3aa7fda7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('word_object_prepositions', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('_word_preposition_uc'))
        batch_op.create_unique_constraint('uq_word_preposition_object', ['word_id', 'preposition_object_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_object_prepositions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_word_preposition_object', type_='unique')
        batch_op.create_index(batch_op.f('_word_preposition_uc'), ['word_id', 'preposition_object_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_table('roles')
    # ### end Alembic commands ###
